meta_title: "Bootrails, a Ruby-on-Rails starter kit"
meta_description: "Instead of blank Ruby-on-Rails, start with Design, Authentication, Admin backend, and many more features."
meta_image: "https://res.cloudinary.com/bdavidxyz-com/image/upload/v1641473825/rails/homeimage.png"
twitter_account: "@https://twitter.com/ShinoKouda"
